module.exports={
  caseType:'reconciled_body_art_service_order',initialState:'request_registered',
  states:['request_registered','health_consent_verified','availability_confirmed','quote_approved','inventory_reserved','payment_authorized','appointment_scheduled','artist_assigned','service_in_progress','service_completed','no_show','partial_service','health_exception','refund_review','refunded','reconciled','closed'],
  createRoles:['booking_agent','studio_manager'],assessmentRoles:['booking_agent','health_safety_reviewer','inventory_reviewer'],auditRoles:['studio_manager','health_safety_reviewer','finance_reviewer','auditor'],connectorRoles:['integration_operator','studio_manager'],
  evidenceKinds:['service_request','age_identity_receipt','health_consent','bloodborne_training_record','sterilization_cycle','cleaning_checklist','availability_snapshot','pricing_tax_quote','inventory_snapshot','payment_authorization','appointment_receipt','artist_assignment','service_record','no_show_record','partial_service_record','health_exception','refund_approval','refund_receipt','accounting_reconciliation','notification_receipt'],
  requiredSignals:['availabilityVersion','pricingVersion','taxVersion','inventoryVersion','scheduleVersion','healthPolicyVersion','policyVersion','rightsStatus','consentStatus','ageIdentityStatus','bloodborneTrainingStatus','sterilizationStatus','inventoryStatus','paymentStatus','artistStatus'],
  professionalBoundary:'Assessment cannot provide medical advice, book, charge, refund, message, or certify health compliance. Authorized studio, health-safety, and finance staff approve consequential actions.',
  connectors:[{name:'payment',purpose:'tokenized authorization and refund receipts'},{name:'tax',purpose:'versioned tax quotes'},{name:'inventory',purpose:'authoritative stock reservations'},{name:'scheduling',purpose:'availability and appointment receipts'},{name:'messaging',purpose:'consented reminder receipts'},{name:'accounting',purpose:'settlement and reconciliation receipts'},{name:'delivery',purpose:'retail fulfillment receipts'},{name:'health_safety_registry',purpose:'training, sterilization, and checklist versions'},{name:'partner',purpose:'approved external service receipts'}],
  transitions:[
    {from:'request_registered',action:'verify_health_consent',to:'health_consent_verified',roles:['health_safety_reviewer'],requiresEvidence:true},
    {from:'health_consent_verified',action:'confirm_availability',to:'availability_confirmed',roles:['booking_agent','integration_operator'],requiresEvidence:true},
    {from:'availability_confirmed',action:'approve_quote',to:'quote_approved',roles:['booking_agent'],requiresEvidence:true},
    {from:'quote_approved',action:'reserve_inventory',to:'inventory_reserved',roles:['inventory_reviewer','integration_operator'],requiresEvidence:true},
    {from:'inventory_reserved',action:'record_payment_authorization',to:'payment_authorized',roles:['finance_reviewer','integration_operator'],requiresEvidence:true,dualControl:true},
    {from:'payment_authorized',action:'record_appointment',to:'appointment_scheduled',roles:['booking_agent','integration_operator'],requiresEvidence:true,dualControl:true},
    {from:'appointment_scheduled',action:'assign_artist',to:'artist_assigned',roles:['studio_manager'],requiresEvidence:true},
    {from:'artist_assigned',action:'start_service',to:'service_in_progress',roles:['artist','studio_manager'],requiresEvidence:true},
    {from:'service_in_progress',action:'record_completion',to:'service_completed',roles:['artist','studio_manager'],requiresEvidence:true},
    {from:'appointment_scheduled',action:'record_no_show',to:'no_show',roles:['booking_agent','studio_manager'],requiresEvidence:true},
    {from:'service_in_progress',action:'record_partial_service',to:'partial_service',roles:['artist','studio_manager'],requiresEvidence:true},
    {from:'service_in_progress',action:'record_health_exception',to:'health_exception',roles:['artist','health_safety_reviewer'],requiresEvidence:true},
    {from:'no_show',action:'submit_refund_review',to:'refund_review',roles:['studio_manager'],requiresEvidence:true},
    {from:'partial_service',action:'submit_refund_review',to:'refund_review',roles:['studio_manager'],requiresEvidence:true},
    {from:'health_exception',action:'submit_refund_review',to:'refund_review',roles:['health_safety_reviewer','studio_manager'],requiresEvidence:true,dualControl:true},
    {from:'refund_review',action:'record_refund',to:'refunded',roles:['finance_reviewer'],requiresEvidence:true,dualControl:true},
    {from:'service_completed',action:'record_reconciliation',to:'reconciled',roles:['finance_reviewer','integration_operator'],requiresEvidence:true,dualControl:true},
    {from:'refunded',action:'record_reconciliation',to:'reconciled',roles:['finance_reviewer','integration_operator'],requiresEvidence:true,dualControl:true},
    {from:'reconciled',action:'close_order',to:'closed',roles:['studio_manager'],requiresEvidence:true}
  ],
  acceptedFixture:{availabilityVersion:'a1',pricingVersion:'p1',taxVersion:'t1',inventoryVersion:'i1',scheduleVersion:'s1',healthPolicyVersion:'h1',policyVersion:'pol1',rightsStatus:'verified',consentStatus:'verified',ageIdentityStatus:'verified',bloodborneTrainingStatus:'current',sterilizationStatus:'passed',inventoryStatus:'reserved',paymentStatus:'authorized',artistStatus:'available'},
  rejectedFixture:{availabilityVersion:'a1',pricingVersion:'p1',taxVersion:'t1',inventoryVersion:'i1',scheduleVersion:'s1',healthPolicyVersion:'h1',policyVersion:'pol1',rightsStatus:'verified',consentStatus:'verified',ageIdentityStatus:'verified',bloodborneTrainingStatus:'expired',sterilizationStatus:'passed',inventoryStatus:'reserved',paymentStatus:'authorized',artistStatus:'available'},
  readyDisposition:'studio_health_and_finance_review_required',holdDisposition:'health_consent_inventory_payment_or_staff_hold',decisionField:'bookingCommand',
  assess:x=>{const ready=x.rightsStatus==='verified'&&x.consentStatus==='verified'&&x.ageIdentityStatus==='verified'&&x.bloodborneTrainingStatus==='current'&&x.sterilizationStatus==='passed'&&x.inventoryStatus==='reserved'&&x.paymentStatus==='authorized'&&x.artistStatus==='available';return{disposition:ready?'studio_health_and_finance_review_required':'health_consent_inventory_payment_or_staff_hold',bookingCommand:null,chargeCommand:null,healthCertification:null,versions:{availability:x.availabilityVersion,pricing:x.pricingVersion,tax:x.taxVersion,inventory:x.inventoryVersion,schedule:x.scheduleVersion,healthPolicy:x.healthPolicyVersion}};}
};
